# Generated by Django 2.2.10 on 2020-11-22 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_auto_20201121_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='contact',
            field=models.TextField(),
        ),
    ]
